-- =============================================================================
-- DataFlowX Baseline Schema Migration
-- Version: V1__initial_schema.sql
-- Database: PostgreSQL 15+
-- =============================================================================

-- 1. Table: users
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL,
    email VARCHAR(254) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL,
    created_at TIMESTAMPTZ(6) NOT NULL,
    updated_at TIMESTAMPTZ(6) NOT NULL,
    CONSTRAINT uk_users_email UNIQUE (email)
);

-- 2. Table: datasets
CREATE TABLE datasets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    description VARCHAR(2000),
    owner_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMPTZ(6) NOT NULL,
    updated_at TIMESTAMPTZ(6) NOT NULL,
    CONSTRAINT fk_datasets_owner_id FOREIGN KEY (owner_id) REFERENCES users (id)
);

CREATE INDEX idx_datasets_owner_id ON datasets (owner_id);

-- 3. Table: jobs
CREATE TABLE jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dataset_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    progress INTEGER NOT NULL,
    submitted_at TIMESTAMPTZ(6) NOT NULL,
    started_at TIMESTAMPTZ(6),
    completed_at TIMESTAMPTZ(6),
    error_message VARCHAR(2000),
    CONSTRAINT fk_jobs_dataset_id FOREIGN KEY (dataset_id) REFERENCES datasets (id),
    CONSTRAINT chk_jobs_progress CHECK (progress >= 0 AND progress <= 100)
);

CREATE INDEX idx_jobs_dataset_id ON jobs (dataset_id);
CREATE INDEX idx_jobs_status ON jobs (status);
CREATE INDEX idx_jobs_submitted_at ON jobs (submitted_at);
